spring:
    application:
        name: ${spring.profiles.active:local}-nomoney-api

aws:
  accessKey: ${AWS_ACCESS_KEY}
  secretKey: ${AWS_SECRET_KEY}

oauth:
  redirect:
    success-url: ${OAUTH_SUCCESS_URL:http://localhost:3000/test/login/result}
    failure-url: ${OAUTH_FAILURE_URL:http://localhost:3000/test/login/error}

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.profiles.active:local}-nomoney-api

---
spring.config.activate.on-profile: local

---
spring.config.activate.on-profile: sandbox

spring:
  config:
    import: 'aws-parameterstore:/sandbox/nomoney/api/'

---
spring.config.activate.on-profile: prod

spring:
  config:
    import: 'aws-parameterstore:/prod/nomoney/api/'

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
